# 1. Import the numpy package under the name `np` 


In [6]:
import numpy as np

# 2. Print the numpy version and the configuration


In [16]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bands/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/bands/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bands/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

# 3. Create a null vector of size 10 

In [17]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 4. How to find the memory size of any array 


In [18]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# 5. How to get the documentation of the numpy add function from the command line? 

In [19]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


# 6. Create a null vector of size 10 but the fifth value which is 1 


In [20]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7. Create a vector with values ranging from 10 to 49 

In [21]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8. Reverse a vector (first element becomes last)

In [22]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# 9. Create a 3x3 matrix with values ranging from 0 to 8 

In [23]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [24]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


# 11. Create a 3x3 identity matrix 

In [25]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 12. Create a 3x3x3 array with random values 

In [26]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.04040078 0.02682542 0.73619104]
  [0.22898047 0.7254619  0.7631205 ]
  [0.79696516 0.98616853 0.51156614]]

 [[0.78531768 0.94407699 0.41186367]
  [0.04081928 0.18320898 0.34186954]
  [0.99362443 0.9874718  0.88960115]]

 [[0.17843805 0.48099354 0.05598863]
  [0.53257527 0.60295932 0.54964914]
  [0.00109455 0.88540914 0.93029148]]]


# 13. Create a 10x10 array with random values and find the minimum and maximum values 

In [27]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.014380681595620448 0.9865121992566002


# 14. Create a random vector of size 30 and find the mean value 

In [28]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5169384953492899


# 15. Create a 2d array with 1 on the border and 0 inside 

In [29]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 16. How to add a border (filled with 0's) around an existing array? 

In [30]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```


In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [33]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [34]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


# 21. Create a checkerboard 8x8 matrix using the tile function 

In [35]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 22. Normalize a 5x5 random matrix 

In [36]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.66233681  1.85091433 -0.05462599 -1.10234779 -1.23309188]
 [ 0.71037749  0.28659803  0.17925322 -0.28197611 -1.28897296]
 [-1.55188647  0.19871467 -1.24622412 -1.53495481  0.76117064]
 [ 0.83283029  1.07519169  0.34222198  1.67401015 -0.64230599]
 [ 0.54953721 -0.77766471  0.22717167 -0.78366101  0.14738368]]


# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [61]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [38]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [39]:

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# 26. What is the output of the following script? 

```python

print(sum(range(5),-1))
from numpy import np
print(sum(range(5),-1))
```


In [45]:
print(sum(range(5), -1))
import numpy as np
print(np.sum(range(5), -1))

TypeError: 'numpy.ndarray' object is not callable

In [41]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: 'numpy.ndarray' object is not callable

# 27. Consider an integer vector Z, which of these expressions are legal? 

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```


In [58]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z <Z> Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```


In [31]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Saachi.Mohanty\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Saachi.Mohanty\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

In [32]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Saachi.Mohanty\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Saachi.Mohanty\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


# 29. How to round away from zero a float array ? 

In [33]:

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 7.  8. 10. -3.  4.  7.  9. -3.  2. 10.]
[ 7.  8. 10. -3.  4.  7.  9. -3.  2. 10.]


# 30. How to find common values between two arrays? 

In [34]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 6 8]


# 31. How to ignore all numpy warnings (not recommended)? 

In [35]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

# 32. Is the following expressions true?

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```


In [37]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Saachi.Mohanty\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

# 33. How to get the dates of yesterday, today and tomorrow?

In [38]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

# 34. How to get all the dates corresponding to the month of July 2016? 

In [39]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? 

In [40]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

# 36. Extract the integer part of a random array of positive numbers using 4 different methods 

In [41]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 4. 1. 0. 9. 9. 5. 6. 4. 0.]
[0. 4. 1. 0. 9. 9. 5. 6. 4. 0.]
[0. 4. 1. 0. 9. 9. 5. 6. 4. 0.]
[0 4 1 0 9 9 5 6 4 0]
[0. 4. 1. 0. 9. 9. 5. 6. 4. 0.]


# 37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [42]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 38. Consider a generator function that generates 10 integers and use it to build an array 

In [43]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [44]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 40. Create a random vector of size 10 and sort it 

In [45]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.24003599 0.29326578 0.4507448  0.55795672 0.61077946 0.6956618
 0.73101499 0.73395949 0.85812206 0.96617262]


# 41. How to sum a small array faster than np.sum? 

In [46]:

Z = np.arange(10)
np.add.reduce(Z)

45

# 42. Consider two random array A and B, check if they are equal

In [47]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 43. Make an array immutable (read-only) 

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [49]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.94360133 0.69712728 0.87741315 0.43268212 0.27213648 0.67601781
 0.7530588  0.90841389 0.86305769 0.88023295]
[0.81265965 0.69028128 1.2558767  0.40122835 0.88966391 1.0014139
 1.39678179 0.42938512 0.82854624 1.34341972]


# 45. Create random vector of size 10 and replace the maximum value by 0 

In [50]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.56364434 0.7090866  0.52453027 0.22913147 0.         0.55732545
 0.14985039 0.21678504 0.04090707 0.12680868]


# 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area 


In [51]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 

In [7]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


# 48. Print the minimum and maximum representable value for each numpy scalar type

In [53]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 49. How to print all the values of an array? 

In [54]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 50. How to find the closest value (to a given scalar) in a vector? 

In [55]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

41


# 51. Create a structured array representing a position (x,y) and a color (r,g,b) 

In [56]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Saachi.Mohanty\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [57]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.45867747 0.33157471 0.70483029 0.38445386 0.44214286
  0.33429466 0.72539569 0.51630471 0.52151168]
 [0.45867747 0.         0.6443566  1.13491625 0.8223253  0.79927303
  0.71134425 1.16350354 0.88110378 0.71838167]
 [0.33157471 0.6443566  0.         0.81904292 0.53921276 0.15767237
  0.59059869 0.81726665 0.74905662 0.83790643]
 [0.70483029 1.13491625 0.81904292 0.         0.32040192 0.77122467
  0.4347955  0.05506993 0.31989582 0.63253938]
 [0.38445386 0.8223253  0.53921276 0.32040192 0.         0.53620308
  0.17793189 0.34259655 0.23477061 0.47052577]
 [0.44214286 0.79927303 0.15767237 0.77122467 0.53620308 0.
  0.63174928 0.7591946  0.76544606 0.90849976]
 [0.33429466 0.71134425 0.59059869 0.4347955  0.17793189 0.63174928
  0.         0.47233353 0.18281646 0.30106242]
 [0.72539569 1.16350354 0.81726665 0.05506993 0.34259655 0.7591946
  0.47233353 0.         0.36956202 0.68298521]
 [0.51630471 0.88110378 0.74905662 0.31989582 0.23477061 0.76544606
  0.18281646 0.369562

# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [58]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[ 6 65 28 55 73 76 16 85 87 83]


# 54. How to read the following file? 

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```


In [59]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


# 55. What is the equivalent of enumerate for numpy arrays? 

In [60]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


# 56. Generate a generic 2D Gaussian-like array 

In [61]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

# 57. How to randomly place p elements in a 2D array? 

In [62]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 58. Subtract the mean of each row of a matrix 

In [63]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.4809418   0.00322029 -0.30078645 -0.49744086  0.18574591 -0.02927621
  -0.12663864  0.13946132 -0.05313293  0.19790577]
 [-0.46699507  0.20636475  0.40135506 -0.5549637   0.19515052  0.10459812
  -0.49644225  0.17153935  0.02327276  0.41612046]
 [ 0.02823029 -0.24252323 -0.0592194   0.05278996 -0.13547263 -0.00189839
   0.3331971   0.29663289  0.09556969 -0.36730628]
 [-0.04094237 -0.23488325  0.01235994 -0.05467658  0.57006262  0.03476045
  -0.01273475  0.44872111 -0.40259313 -0.32007404]
 [-0.04572368  0.37998786  0.40113107 -0.2213739  -0.35972343 -0.04610037
  -0.45147962  0.41181162  0.19480915 -0.2633387 ]]


# 59. How to sort an array by the nth column? 

In [64]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 1 1]
 [0 0 7]
 [6 8 3]]
[[0 0 7]
 [6 1 1]
 [6 8 3]]


# 60. How to tell if a given 2D array has null columns? 

In [65]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


# 61. Find the nearest value from a given value in an array 

In [66]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5681629779778025


# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

In [67]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# 63. Create an array class that has a name attribute 

In [68]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [69]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[2. 3. 6. 5. 2. 4. 1. 4. 2. 1.]
[ 3.  5. 11.  9.  3.  7.  1.  7.  3.  1.]


# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 

In [70]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

In [9]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

64


# 67. Considering a four dimensions array, how to get sum over the last two axis at once? 

In [10]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[61 38 52 47]
 [55 32 46 49]
 [61 62 43 53]]
[[61 38 52 47]
 [55 32 46 49]
 [61 62 43 53]]


# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? 


In [73]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.59932694 0.60654897 0.70327047 0.58231594 0.58671835 0.42465284
 0.46853423 0.49256541 0.60013607 0.5177148 ]
0    0.599327
1    0.606549
2    0.703270
3    0.582316
4    0.586718
5    0.424653
6    0.468534
7    0.492565
8    0.600136
9    0.517715
dtype: float64


# 69. How to get the diagonal of a dot product? 

In [74]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.65740834, 1.81718508, 1.01450372, 0.73057696, 1.1335166 ])

# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [75]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [76]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# 72. How to swap two rows of an array? 

In [77]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles 

In [78]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 14) ( 4, 56) ( 8, 25) ( 8, 45) (14, 56) (15, 43) (15, 87) (17, 45)
 (17, 49) (25, 39) (25, 45) (25, 49) (31, 38) (31, 48) (33, 45) (33, 53)
 (33, 76) (33, 95) (38, 48) (39, 49) (40, 40) (40, 92) (43, 87) (45, 49)
 (45, 76) (51, 57) (51, 78) (53, 95) (57, 78)]


# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [79]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


# 75. How to compute averages using a sliding window over an array? 

In [12]:
def moving_average(arr, window_size):
    if window_size <= 0 or window_size > len(arr):
        raise ValueError("Invalid window size")

    window_averages = []
    window_sum = sum(arr[:window_size])

    for i in range(len(arr) - window_size + 1):
        if i > 0:
            window_sum = window_sum - arr[i - 1] + arr[i + window_size - 1]
        window_average = window_sum / window_size
        window_averages.append(window_average)

    return window_averages

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
window_size = 3
averages = moving_average(arr, window_size)
print(averages)

TypeError: 'numpy.ndarray' object is not callable

# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

# 77. How to negate a boolean, or to change the sign of a float inplace? 

In [ ]:

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 

In [134]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.08006744e-01 7.31959079e+00 6.19400968e+00 2.44678067e+00
  5.47958302e+00 4.49056454e+00 2.01636808e+00 2.52722620e+00
  9.27020276e-01 7.09962192e+00]
 [1.11691716e+01 4.54270455e+00 3.48763795e+00 8.91001530e+00
  6.38849971e+00 6.72964082e+00 8.89213099e+00 1.21028823e+00
  8.70326791e+00 6.41315616e-02]
 [3.06931555e-01 5.42534331e+00 7.79692568e+00 2.54191813e+00
  4.54591647e+00 4.75995760e+00 2.62927753e+00 2.30388699e+00
  2.98711840e+00 1.00664877e+01]
 [6.37996360e+00 1.60229657e+00 2.05188879e+00 4.19187664e+00
  2.48798845e+00 1.89336580e+00 3.84024666e+00 3.07045610e+00
  8.68542896e+00 5.88635010e+00]
 [2.11218375e+00 1.97153925e+00 9.02366549e+00 1.36928300e-01
  6.36614941e-01 2.51793529e+00 1.25921337e+00 1.37841864e+01
  1.44737837e+01 1.51148412e+01]
 [1.03720543e+01 1.47793889e+01 1.72776836e+01 1.26164259e+01
  1.44682691e+01 1.48161364e+01 1.26118839e+01 3.97465866e+00
  3.21360780e+00 1.80125632e+01]
 [4.32705932e+00 4.44968477e+00 1.16414242e+00 1.92981897e

# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) 

In [82]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 6 9 8 0 4 4 0 6 5]
 [6 6 8 0 6 7 3 8 7 8]
 [3 0 4 5 9 1 5 8 7 6]
 [4 3 6 4 4 1 5 3 9 6]
 [7 4 6 4 5 8 2 3 3 6]
 [0 0 4 0 3 0 3 8 8 4]
 [8 6 5 3 0 1 2 6 5 1]
 [1 2 9 9 3 1 3 8 7 9]
 [4 7 4 0 4 8 9 3 6 9]
 [8 8 2 0 0 5 7 5 6 7]]
[[0 0 0 0 0]
 [0 4 6 9 8]
 [0 6 6 8 0]
 [0 3 0 4 5]
 [0 4 3 6 4]]


C:\Users\Saachi.Mohanty\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 


In [136]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


Z = np.arange(1, 15, dtype=np.uint32)
print(stride_tricks(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


TypeError: 'module' object is not callable

# 82. Compute a matrix rank

In [84]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


# 83. How to find the most frequent value in an array?

In [85]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [15]:
import numpy as np

random_matrix = np.random.rand(10, 10)

block_size = 3

blocks = []

for i in range(10 - block_size + 1):
    for j in range(10 - block_size + 1):
        block = random_matrix[i:i+block_size, j:j+block_size]
        blocks.append(block)

for block in blocks:
    print(block)

[[0.62285291 0.27932265 0.31261087]
 [0.71042213 0.30551568 0.93707061]
 [0.30712601 0.94430075 0.09930276]]
[[0.27932265 0.31261087 0.98918199]
 [0.30551568 0.93707061 0.67525722]
 [0.94430075 0.09930276 0.51219912]]
[[0.31261087 0.98918199 0.38885964]
 [0.93707061 0.67525722 0.68717353]
 [0.09930276 0.51219912 0.83266497]]
[[0.98918199 0.38885964 0.43412502]
 [0.67525722 0.68717353 0.17300558]
 [0.51219912 0.83266497 0.78235205]]
[[0.38885964 0.43412502 0.04088205]
 [0.68717353 0.17300558 0.24799876]
 [0.83266497 0.78235205 0.47258742]]
[[0.43412502 0.04088205 0.20705726]
 [0.17300558 0.24799876 0.94699975]
 [0.78235205 0.47258742 0.889419  ]]
[[0.04088205 0.20705726 0.23302382]
 [0.24799876 0.94699975 0.60603411]
 [0.47258742 0.889419   0.35773028]]
[[0.20705726 0.23302382 0.64028883]
 [0.94699975 0.60603411 0.83861339]
 [0.889419   0.35773028 0.7397173 ]]
[[0.71042213 0.30551568 0.93707061]
 [0.30712601 0.94430075 0.09930276]
 [0.57010537 0.67272776 0.90488716]]
[[0.30551568 0.9370

# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] 

In [87]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 11  8 14  3]
 [11  5 10  7  6]
 [ 8 10  2 42 16]
 [14  7 42  8  9]
 [ 3  6 16  9  1]]


# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [88]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

# 88. How to implement the Game of Life using numpy arrays? 

In [90]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0

# 89. How to get the n largest values of an array

In [91]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9999 9997 9998 9995]


# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

In [92]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# 91. How to create a record array from a regular array? 

In [93]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [94]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.22 s ± 34.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
593 ms ± 42.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
343 ms ± 35.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [95]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 7]


# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [96]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 1 2]
 [2 2 2]
 [4 0 1]
 [4 2 1]
 [3 1 1]
 [0 0 1]
 [0 1 3]
 [4 2 3]
 [2 2 0]
 [0 1 2]]
[[2 1 2]
 [4 0 1]
 [4 2 1]
 [3 1 1]
 [0 0 1]
 [0 1 3]
 [4 2 3]
 [2 2 0]
 [0 1 2]]
[[2 1 2]
 [4 0 1]
 [4 2 1]
 [3 1 1]
 [0 0 1]
 [0 1 3]
 [4 2 3]
 [2 2 0]
 [0 1 2]]


# 95. Convert a vector of ints into a matrix binary representation 

In [97]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# 96. Given a two dimensional array, how to extract unique rows?

In [98]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [99]:

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.38583322, 0.33338107, 0.19556621, 0.12385202, 0.10041208,
        0.01333355, 0.37506635, 0.3069225 , 0.38882191, 0.44656913],
       [0.28188939, 0.2435679 , 0.14288049, 0.09048617, 0.07336098,
        0.00974148, 0.27402313, 0.22423729, 0.28407293, 0.32626299],
       [0.62607649, 0.54096443, 0.31733765, 0.20096983, 0.16293477,
        0.02163583, 0.60860552, 0.49803114, 0.63092612, 0.72463028],
       [0.45874395, 0.39637993, 0.23252227, 0.14725628, 0.11938691,
        0.01585318, 0.44594247, 0.3649215 , 0.46229741, 0.5309571 ],
       [0.44605393, 0.38541507, 0.22609012, 0.1431828 , 0.11608437,
        0.01541465, 0.43360658, 0.35482685, 0.4495091 , 0.51626949],
       [0.64957034, 0.56126441, 0.32924591, 0.20851133, 0.16904898,
        0.02244773, 0.63144376, 0.51672003, 0.65460196, 0.75182242],
       [0.29325961, 0.25339239, 0.14864368, 0.094136  , 0.07632004,
        0.01013441, 0.28507605, 0.23328207, 0.29553122, 0.33942305],
       [0.80791771, 0.69808522, 0.409507 

# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

In [100]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [101]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 

In [102]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.08569007  0.28374036]
